// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xzmewvnjjljzigkcrezf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6bWV3dm5qamxqemlna2NyZXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0ODQ5MDgsImV4cCI6MjA5MzA2MDkwOH0.-_mqaSZaWdipmaRKLHBbCjyFs2OIb2RvLiMZ_PseIYU";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);